'use client'
import { useState } from 'react'
import Link from 'next/link'
import { CalendarDays, CheckCircle2, Clock3, Loader2, Video, MapPin } from 'lucide-react'
import { createTraineeBooking } from '@/app/auth/actions'

type Slot = { start: string; end: string; label: string }
type Service = { id:string; title:string; price:number; duration_minutes:number; mode:string }
export function RealBookingForm({ trainer, services, slots }: { trainer:any; services:Service[]; slots:Slot[] }) {
 const [serviceId,setServiceId]=useState(services[0]?.id||''); const service=services.find(s=>s.id===serviceId)||services[0]
 const modes=service?.mode==='both'?['online','in_person']:service?.mode?[service.mode]:[]
 const [mode,setMode]=useState<'online'|'in_person'>((modes[0]||'online') as any); const [selected,setSelected]=useState(''); const [note,setNote]=useState(''); const [busy,setBusy]=useState(false); const [done,setDone]=useState(false); const [error,setError]=useState('')
 async function submit(){ if(!selected||!service)return; setBusy(true);setError(''); const r=await createTraineeBooking({trainerId:trainer.id,serviceId:service.id,start:selected,mode,note}); setBusy(false); if(r.status==='success')setDone(true); else setError(r.message) }
 if(done)return <div className="rounded-[2rem] border border-border bg-card p-8 text-center"><CheckCircle2 className="mx-auto size-14 text-primary"/><h2 className="mt-5 text-2xl font-extrabold">تم إرسال طلب الحجز</h2><p className="mt-3 leading-7 text-muted-foreground">بانتظار رد المدرب. ستظهر حالة الطلب في لوحة حسابك.</p><Link href="/dashboard" className="mt-6 inline-flex h-12 items-center justify-center rounded-xl bg-primary px-7 font-bold text-primary-foreground">الذهاب للوحة حسابي</Link></div>
 return <div className="rounded-[2rem] border border-border bg-card p-6 shadow-xl sm:p-8"><h1 className="text-2xl font-extrabold">احجز جلستك مع {trainer.display_name}</h1><p className="mt-2 text-sm text-muted-foreground">اختر الخدمة والموعد وطريقة التدريب.</p>
 <div className="mt-7"><label className="text-sm font-bold">الخدمة</label><div className="mt-2 space-y-2">{services.map(s=><button key={s.id} onClick={()=>{setServiceId(s.id);setMode((s.mode==='both'?'online':s.mode) as any);setSelected('')}} className={`w-full rounded-xl border p-4 text-right ${serviceId===s.id?'border-primary bg-primary/5 ring-1 ring-primary':''}`}><div className="flex justify-between gap-3"><span className="font-extrabold">{s.title}</span><span className="font-extrabold">{Number(s.price).toLocaleString('ar-SA')} ر.س</span></div><div className="mt-1 text-xs text-muted-foreground">{s.duration_minutes} دقيقة</div></button>)}</div></div>
 <div className="mt-7"><label className="text-sm font-bold">طريقة التدريب</label><div className="mt-2 flex gap-2">{modes.map(m=><button key={m} onClick={()=>setMode(m as any)} className={`flex-1 rounded-xl border px-4 py-3 text-sm font-bold ${mode===m?'border-primary bg-primary/5 text-primary':''}`}>{m==='online'?<><Video className="mr-1 inline size-4"/>أونلاين</>:<><MapPin className="mr-1 inline size-4"/>حضوري</>}</button>)}</div></div>
 <div className="mt-7"><label className="text-sm font-bold">المواعيد المتاحة</label><div className="mt-2 grid gap-2 sm:grid-cols-2">{slots.map(s=><button key={s.start} onClick={()=>setSelected(s.start)} className={`rounded-xl border p-4 text-right ${selected===s.start?'border-primary bg-primary/5 ring-1 ring-primary':''}`}><CalendarDays className="mr-2 inline size-4"/><span className="font-bold">{s.label}</span><div className="mt-1 text-xs text-muted-foreground"><Clock3 className="mr-1 inline size-3.5"/>{new Date(s.start).toLocaleTimeString('ar-SA',{hour:'numeric',minute:'2-digit'})}</div></button>)}</div>{!slots.length&&<p className="mt-3 rounded-xl bg-secondary p-4 text-sm text-muted-foreground">لا توجد مواعيد منشورة حالياً.</p>}</div>
 <div className="mt-7"><label className="text-sm font-bold">ملاحظة للمدرب <span className="font-normal text-muted-foreground">(اختياري)</span></label><textarea value={note} onChange={e=>setNote(e.target.value)} className="field mt-2 min-h-24 w-full" placeholder="مثلاً: مستواي مبتدئ وأرغب بالتركيز على..."/></div>
 {error&&<div className="mt-4 rounded-xl bg-destructive/10 p-3 text-sm font-bold text-destructive">{error}</div>}<button disabled={!selected||busy} onClick={submit} className="mt-6 flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-primary font-bold text-primary-foreground disabled:opacity-50">{busy?<><Loader2 className="size-4 animate-spin"/>جاري إرسال الطلب...</>:'إرسال طلب الحجز'}</button><p className="mt-3 text-center text-xs text-muted-foreground">سيظهر الطلب للمدرب أولاً، ولا يتم تأكيد الموعد إلا بعد قبوله.</p></div>
}
