'use client'

import { useState } from 'react'
import { CalendarDays, Check, Clock3, Plus, Save, Trash2 } from 'lucide-react'
import { saveTrainerAvailability, saveTrainerService, toggleTrainerService, updateTrainerProfile } from '@/app/auth/actions'

type Category = { id: string; name_ar: string }
type Service = { id: string; category_id: string; title: string; description: string | null; duration_minutes: number; price: number; mode: string; active: boolean }
type Slot = { id?: string; weekday: number; start_time: string; end_time: string; active: boolean }

const days = ['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت']

export function TrainerDashboard({ trainer, categories, services, availability }: { trainer: any; categories: Category[]; services: Service[]; availability: Slot[] }) {
  const [tab, setTab] = useState<'overview'|'profile'|'services'|'availability'>('overview')
  const [notice, setNotice] = useState('')
  const [profile, setProfile] = useState({ displayName: trainer.display_name || '', bio: trainer.bio || '', city: trainer.city || '', trainingMode: trainer.training_mode || 'both' })
  const [service, setService] = useState({ categoryId: categories[0]?.id || '', title: '', description: '', durationMinutes: 60, price: 150, mode: 'both' })
  const [slots, setSlots] = useState(availability.map(s => ({ weekday: s.weekday, startTime: s.start_time.slice(0,5), endTime: s.end_time.slice(0,5) })))
  const flash = (message: string) => { setNotice(message); setTimeout(() => setNotice(''), 3500) }

  async function profileSubmit(e: React.FormEvent) { e.preventDefault(); const r = await updateTrainerProfile(profile as any); flash(r.status === 'success' ? 'تم حفظ بيانات الملف.' : r.message) }
  async function serviceSubmit(e: React.FormEvent) { e.preventDefault(); const r = await saveTrainerService(service as any); flash(r.status === 'success' ? 'تم حفظ الخدمة.' : r.message); if (r.status === 'success') setService({ ...service, title:'', description:'' }) }
  function addSlot() { setSlots([...slots, { weekday: 0, startTime:'16:00', endTime:'17:00' }]) }
  function updateSlot(i:number, key:string, value:string|number) { setSlots(slots.map((s,idx)=>idx===i ? {...s,[key]:value}:s)) }
  async function availabilitySubmit(e: React.FormEvent) { e.preventDefault(); const r = await saveTrainerAvailability(slots); flash(r.status === 'success' ? 'تم حفظ المواعيد المتاحة.' : r.message) }

  if (!trainer.verified) return <div className="rounded-3xl border border-border bg-card p-8 text-center"><div className="mx-auto flex size-14 items-center justify-center rounded-2xl bg-primary/10 text-primary"><Clock3 className="size-7" /></div><h2 className="mt-5 text-2xl font-extrabold">طلبك قيد المراجعة</h2><p className="mx-auto mt-3 max-w-lg leading-7 text-muted-foreground">بعد اعتمادك من فريق لَوَّان ستظهر لك لوحة المدرب الكاملة لإضافة الخدمات والأسعار والمواعيد واستقبال الحجوزات.</p><div className="mt-6 inline-flex items-center gap-2 rounded-full bg-secondary px-4 py-2 text-sm font-bold"><Check className="size-4" /> تم استلام الطلب</div></div>

  return <div>
    {notice && <div className="fixed bottom-5 left-5 z-50 rounded-xl bg-foreground px-5 py-3 text-sm font-bold text-background shadow-xl">{notice}</div>}
    <div className="grid gap-5 lg:grid-cols-[240px_1fr]">
      <aside className="h-fit rounded-2xl border border-border bg-card p-3"><div className="px-3 py-4"><p className="text-xs font-bold text-primary">لوحة المدرب</p><h2 className="mt-1 text-lg font-extrabold">{trainer.display_name || 'مدربي لَوَّان'}</h2></div>{[['overview','نظرة عامة'],['profile','ملفي الشخصي'],['services','الخدمات والأسعار'],['availability','المواعيد المتاحة']].map(([id,label])=><button key={id} onClick={()=>setTab(id as any)} className={`w-full rounded-xl px-3 py-3 text-right text-sm font-bold ${tab===id?'bg-primary text-primary-foreground':'hover:bg-secondary'}`}>{label}</button>)}</aside>
      <section>
        {tab==='overview' && <div className="space-y-5"><div className="rounded-3xl border border-border bg-card p-7"><p className="text-sm font-bold text-primary">مرحباً بك</p><h1 className="mt-1 text-3xl font-extrabold">خلّ لَوَّان يوصّل موهبتك للطلاب.</h1><p className="mt-3 max-w-2xl leading-7 text-muted-foreground">أكمل الخدمات والأسعار والمواعيد حتى يصبح ملفك جاهزاً لاستقبال الحجوزات.</p></div><div className="grid gap-4 sm:grid-cols-3"><Metric title="الخدمات النشطة" value={services.filter(s=>s.active).length}/><Metric title="إجمالي الخدمات" value={services.length}/><Metric title="التقييم" value={trainer.rating ? `${trainer.rating} ★` : 'جديد'}/></div><div className="rounded-2xl border border-border bg-card p-6"><h2 className="text-xl font-extrabold">خطوتك التالية</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><Action onClick={()=>setTab('profile')} title="أكمل ملفك" text="الاسم، النبذة، المدينة وطريقة التدريب"/><Action onClick={()=>setTab('services')} title="أضف أول خدمة" text="حدد المهارة، السعر ومدة الحصة"/><Action onClick={()=>setTab('availability')} title="حدد أوقاتك" text="اختر الأيام والساعات التي تستقبل فيها الطلاب"/></div></div></div>}
        {tab==='profile' && <Panel title="ملفي الشخصي" subtitle="هذه المعلومات تظهر للطلاب في صفحة المدرب."><form onSubmit={profileSubmit} className="space-y-5"><Field label="اسم العرض"><input className="field" value={profile.displayName} onChange={e=>setProfile({...profile,displayName:e.target.value})}/></Field><Field label="المدينة"><input className="field" value={profile.city} onChange={e=>setProfile({...profile,city:e.target.value})} placeholder="الخبر"/></Field><Field label="النبذة"><textarea className="field min-h-32" value={profile.bio} onChange={e=>setProfile({...profile,bio:e.target.value})}/></Field><Field label="طريقة التدريب"><select className="field" value={profile.trainingMode} onChange={e=>setProfile({...profile,trainingMode:e.target.value})}><option value="both">حضوري + أونلاين</option><option value="online">أونلاين</option><option value="in_person">حضوري</option></select></Field><button className="btn"><Save className="size-4"/> حفظ التغييرات</button></form></Panel>}
        {tab==='services' && <div className="space-y-5"><Panel title="إضافة خدمة" subtitle="السعر تحدده أنت، ولَوَّان يحتسب العمولة عند إتمام الحجز."><form onSubmit={serviceSubmit} className="grid gap-4 sm:grid-cols-2"><Field label="المجال"><select className="field" value={service.categoryId} onChange={e=>setService({...service,categoryId:e.target.value})}>{categories.map(c=><option key={c.id} value={c.id}>{c.name_ar}</option>)}</select></Field><Field label="اسم الخدمة"><input className="field" value={service.title} onChange={e=>setService({...service,title:e.target.value})} placeholder="مثال: تعليم البيانو للمبتدئين"/></Field><Field label="السعر بالريال"><input className="field" type="number" min="1" value={service.price} onChange={e=>setService({...service,price:Number(e.target.value)})}/></Field><Field label="مدة الحصة"><select className="field" value={service.durationMinutes} onChange={e=>setService({...service,durationMinutes:Number(e.target.value)})}><option value="30">30 دقيقة</option><option value="45">45 دقيقة</option><option value="60">60 دقيقة</option><option value="90">90 دقيقة</option><option value="120">120 دقيقة</option></select></Field><Field label="طريقة تقديم الخدمة"><select className="field" value={service.mode} onChange={e=>setService({...service,mode:e.target.value})}><option value="both">حضوري + أونلاين</option><option value="online">أونلاين</option><option value="in_person">حضوري</option></select></Field><Field label="الوصف"><textarea className="field min-h-24" value={service.description} onChange={e=>setService({...service,description:e.target.value})}/></Field><div className="sm:col-span-2"><button className="btn"><Plus className="size-4"/> إضافة الخدمة</button></div></form></Panel><Panel title="خدماتي" subtitle="يمكنك إيقاف الخدمة مؤقتاً بدون حذفها."><div className="space-y-3">{services.length===0?<p className="text-sm text-muted-foreground">لا توجد خدمات بعد.</p>:services.map(s=><div key={s.id} className="flex flex-col gap-3 rounded-xl border border-border p-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="font-extrabold">{s.title}</div><div className="mt-1 text-sm text-muted-foreground">{s.duration_minutes} دقيقة · {Number(s.price).toLocaleString('ar-SA')} ر.س</div></div><button onClick={async()=>{const r=await toggleTrainerService(s.id,!s.active); flash(r.status==='success'?'تم تحديث حالة الخدمة.':r.message)}} className={`rounded-lg px-3 py-2 text-xs font-bold ${s.active?'bg-primary/10 text-primary':'bg-secondary text-muted-foreground'}`}>{s.active?'نشطة':'متوقفة'}</button></div>)}</div></Panel></div>}
        {tab==='availability' && <Panel title="المواعيد المتاحة" subtitle="أضف الفترات الأسبوعية التي يستطيع الطالب حجزها."><form onSubmit={availabilitySubmit} className="space-y-3">{slots.map((s,i)=><div key={i} className="grid gap-2 rounded-xl border border-border p-3 sm:grid-cols-[1fr_1fr_1fr_auto] sm:items-center"><select className="field" value={s.weekday} onChange={e=>updateSlot(i,'weekday',Number(e.target.value))}>{days.map((d,n)=><option key={d} value={n}>{d}</option>)}</select><input className="field" type="time" value={s.startTime} onChange={e=>updateSlot(i,'startTime',e.target.value)}/><input className="field" type="time" value={s.endTime} onChange={e=>updateSlot(i,'endTime',e.target.value)}/><button type="button" onClick={()=>setSlots(slots.filter((_,idx)=>idx!==i))} className="flex size-10 items-center justify-center rounded-lg border border-border text-muted-foreground hover:text-destructive"><Trash2 className="size-4"/></button></div>)}<div className="flex flex-wrap gap-3 pt-2"><button type="button" onClick={addSlot} className="rounded-xl border border-border px-4 py-3 text-sm font-bold"><Plus className="mr-1 inline size-4"/> إضافة فترة</button><button className="btn"><Save className="size-4"/> حفظ المواعيد</button></div></form></Panel>}
      </section>
    </div>
  </div>
}
function Metric({title,value}:{title:string,value:string|number}){return <div className="rounded-2xl border border-border bg-card p-5"><div className="text-2xl font-extrabold">{value}</div><div className="mt-1 text-sm text-muted-foreground">{title}</div></div>}
function Action({title,text,onClick}:{title:string,text:string,onClick:()=>void}){return <button onClick={onClick} className="rounded-xl border border-border p-4 text-right hover:bg-secondary"><div className="font-extrabold">{title}</div><div className="mt-1 text-xs leading-5 text-muted-foreground">{text}</div></button>}
function Panel({title,subtitle,children}:{title:string,subtitle:string,children:React.ReactNode}){return <div className="rounded-2xl border border-border bg-card p-6"><h2 className="text-2xl font-extrabold">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{subtitle}</p><div className="mt-6">{children}</div></div>}
function Field({label,children}:{label:string,children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-sm font-bold">{label}</span>{children}</label>}
