import Link from 'next/link'
import { MapPin, Star, SlidersHorizontal } from 'lucide-react'
import { SiteHeader } from '@/components/lawwan/header'
import { ValidationBanner } from '@/components/lawwan/validation-banner'
import { categories, trainers } from '@/lib/lawwan-data'

export default async function TrainersPage({ searchParams }: { searchParams: Promise<{ category?: string }> }) {
  const params = await searchParams
  const category = params.category
  const filtered = category ? trainers.filter((t) => t.category === category) : trainers
  return <div className="min-h-svh bg-background"><SiteHeader /><ValidationBanner /><main className="mx-auto max-w-7xl px-5 py-10 lg:px-8"><div className="max-w-2xl"><p className="text-sm font-bold text-primary">اكتشف</p><h1 className="mt-2 text-4xl font-extrabold">ابحث عن مدربك</h1><p className="mt-3 leading-7 text-muted-foreground">اختر المجال والمدرب المناسب لك، ثم اطلع على التفاصيل والمواعيد قبل الحجز.</p><p className="mt-4 rounded-xl border border-accent/30 bg-accent/10 px-4 py-3 text-xs font-medium leading-6">تنبيه: هذه صفحة تجريبية للتحقق من جدوى المشروع، وجميع بيانات المدربين المعروضة حاليًا افتراضية وغير حقيقية.</p></div><div className="mt-8 flex gap-2 overflow-x-auto pb-2"> <Link href="/trainers" className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-bold ${!category ? 'bg-primary text-primary-foreground' : 'border border-border bg-card'}`}>الكل</Link>{categories.map(c => <Link key={c.name} href={`/trainers?category=${encodeURIComponent(c.name)}`} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-bold ${category === c.name ? 'bg-primary text-primary-foreground' : 'border border-border bg-card'}`}>{c.icon} {c.name}</Link>)}</div><div className="mt-8 flex items-center justify-between"><span className="text-sm text-muted-foreground">{filtered.length} مدربين متاحين</span><button className="flex items-center gap-2 rounded-xl border border-border bg-card px-4 py-2 text-sm font-bold"><SlidersHorizontal className="size-4" /> تصفية</button></div><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(t => <Link key={t.id} href={`/trainers/${t.id}`} className="group rounded-2xl border border-border bg-card p-5 transition hover:-translate-y-1 hover:shadow-xl"><div className="flex gap-4"><div className="flex size-20 shrink-0 items-center justify-center rounded-2xl bg-primary text-lg font-extrabold text-primary-foreground">{t.initials}</div><div className="min-w-0"><div className="flex items-start justify-between gap-2"><h2 className="font-extrabold">{t.name}</h2><span className="flex shrink-0 items-center gap-1 text-xs font-bold"><Star className="size-3.5 fill-current" /> {t.rating}</span></div><p className="mt-1 text-sm text-muted-foreground">{t.specialty}</p><p className="mt-2 text-xs text-muted-foreground"><MapPin className="mr-1 inline size-3" />{t.city} · {t.mode}</p></div></div><p className="mt-5 line-clamp-2 text-sm leading-6 text-muted-foreground">{t.bio}</p><div className="mt-5 flex items-center justify-between border-t border-border pt-4"><span className="text-xs text-muted-foreground">{t.reviews} تقييم</span><span className="font-extrabold">{t.price} ر.س <span className="text-xs font-normal text-muted-foreground">/ جلسة</span></span></div></Link>)}</div></main></div>
}
