import Link from 'next/link'
import { notFound } from 'next/navigation'
import { ArrowRight, CalendarDays, CheckCircle2, Clock3, MapPin, Star, Video } from 'lucide-react'
import { SiteHeader } from '@/components/lawwan/header'
import { trainers } from '@/lib/lawwan-data'

export default async function TrainerPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const trainer = trainers.find(t => t.id === id)
  if (!trainer) notFound()
  return <div className="min-h-svh bg-background"><SiteHeader /><main className="mx-auto max-w-6xl px-5 py-8 lg:px-8"><Link href="/trainers" className="inline-flex items-center gap-2 text-sm font-bold text-muted-foreground hover:text-foreground"><ArrowRight className="size-4" /> كل المدربين</Link><div className="mt-7 grid gap-6 lg:grid-cols-[1fr_360px]"><section><div className="rounded-[2rem] border border-border bg-card p-7 sm:p-9"><div className="flex flex-col gap-6 sm:flex-row sm:items-center"><div className="flex size-28 shrink-0 items-center justify-center rounded-[1.75rem] bg-primary text-2xl font-extrabold text-primary-foreground">{trainer.initials}</div><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-3xl font-extrabold">{trainer.name}</h1><span className="rounded-full bg-primary/10 px-2.5 py-1 text-xs font-bold text-primary">مدرب معتمد</span></div><p className="mt-2 text-lg text-muted-foreground">{trainer.specialty}</p><div className="mt-3 flex flex-wrap gap-4 text-sm text-muted-foreground"><span><Star className="mr-1 inline size-4 fill-current" />{trainer.rating} ({trainer.reviews} تقييم)</span><span><MapPin className="mr-1 inline size-4" />{trainer.city}</span><span>{trainer.mode}</span></div></div></div><div className="mt-8 border-t border-border pt-7"><h2 className="text-lg font-extrabold">عن المدرب</h2><p className="mt-3 leading-8 text-muted-foreground">{trainer.bio} في لَوَّان، تبدأ الجلسة من احتياجك ومستواك الحالي، ثم نضع خطوات عملية تساعدك على الاستمرار والتطور.</p></div><div className="mt-8 border-t border-border pt-7"><h2 className="text-lg font-extrabold">ماذا ستحصل عليه؟</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><Benefit text="جلسة فردية مخصصة لمستواك" /><Benefit text="خطة واضحة لكل جلسة" /><Benefit text="إمكانية الحضور أو التعلم أونلاين" /><Benefit text="متابعة وتقييم للتقدم" /></div></div></div></section><aside className="h-fit rounded-[2rem] border border-border bg-card p-6 shadow-lg shadow-foreground/5"><div className="flex items-end justify-between"><div><p className="text-sm text-muted-foreground">سعر الجلسة</p><p className="mt-1 text-3xl font-extrabold">{trainer.price} <span className="text-sm font-medium">ر.س</span></p></div><span className="text-xs text-muted-foreground">60 دقيقة</span></div><div className="mt-6 space-y-3"><Slot date="الثلاثاء 8 سبتمبر" time="7:00 م" online={trainer.mode.includes('أونلاين')} /><Slot date="الأربعاء 9 سبتمبر" time="6:00 م" online={trainer.mode.includes('أونلاين')} /><Slot date="الخميس 10 سبتمبر" time="8:00 م" online={trainer.mode.includes('أونلاين')} /></div><Link href={`/book/${trainer.id}`} className="mt-5 flex h-12 items-center justify-center gap-2 rounded-xl bg-primary font-bold text-primary-foreground">اختر موعدك <CalendarDays className="size-4" /></Link><p className="mt-3 text-center text-xs leading-5 text-muted-foreground">لن يتم خصم أي مبلغ في هذه النسخة التجريبية.</p></aside></div></main></div>
}
function Benefit({ text }: { text: string }) { return <div className="flex items-center gap-2 rounded-xl bg-secondary p-3 text-sm font-medium"><CheckCircle2 className="size-4 shrink-0 text-primary" />{text}</div> }
function Slot({ date, time, online }: { date: string; time: string; online: boolean }) { return <div className="rounded-xl border border-border p-3"><div className="flex items-center justify-between"><span className="text-sm font-bold">{date}</span><span className="text-xs font-bold text-primary">متاح</span></div><div className="mt-2 flex items-center gap-4 text-xs text-muted-foreground"><span><Clock3 className="mr-1 inline size-3.5" />{time}</span>{online && <span><Video className="mr-1 inline size-3.5" />أونلاين</span>}</div></div> }
